parameters:
    ezprice.fieldType.ezprice.class: EzSystems\EzPriceBundle\eZ\Publish\Core\FieldType\Price\Type
    ezprice.fieldType.ezprice.converter.class: EzSystems\EzPriceBundle\eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Price
    ezprice.twig.extension.class: EzSystems\EzPriceBundle\Twig\Extension\PriceExtension
    ezprice.api.service.vatservice.class: EzSystems\EzPriceBundle\Core\Price\VatService
    ezprice.api.service.contentvatservice.class: EzSystems\EzPriceBundle\Core\Price\ContentVatService
    ezprice.api.service.pricewithvatcalculator.class: EzSystems\EzPriceBundle\Core\Price\PriceValueWithVatDataCalculator
    ezprice.api.storage_engine.legacy.handler.ezprice.vathandler.factory.class: EzSystems\EzPriceBundle\ApiLoader\LegacyVatHandlerFactory
    ezprice.api.storage_engine.legacy.handler.ezprice.vathandler.class: EzSystems\EzPriceBundle\Core\Persistence\Legacy\Price\Vat\VatHandler
    ezprice.api.storage_engine.legacy.handler.ezprice.contentvathandler.factory.class: EzSystems\EzPriceBundle\ApiLoader\LegacyContentVatHandlerFactory
    ezprice.api.storage_engine.legacy.handler.ezprice.contentvathandler.class: EzSystems\EzPriceBundle\Core\Persistence\Legacy\Price\ContentVat\ContentVatHandler

services:
    ezprice.fieldType.ezprice.class:
        parent: ezpublish.fieldType
        class: '%ezprice.fieldType.ezprice.class%'
        tags:
            - {name: ezpublish.fieldType, alias: ezprice}

    ezprice.fieldType.ezprice.converter:
        class: '%ezprice.fieldType.ezprice.converter.class%'
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: ezprice, lazy: true, callback: '::create'}

    ezprice.twig.extension:
        class: '%ezprice.twig.extension.class%'
        tags:
            - { name: twig.extension }
        arguments:
            - '@ezprice.api.service.contentvatservice'
            - '@ezprice.api.service.pricewithvatcalculator'
            - '@?logger'

    ezprice.api.service.vatservice:
        class: '%ezprice.api.service.vatservice.class%'
        arguments:
            - '@ezprice.api.storage_engine.legacy.handler.ezprice.vathandler'

    ezprice.api.service.contentvatservice:
        class: '%ezprice.api.service.contentvatservice.class%'
        arguments:
            - '@ezprice.api.storage_engine.legacy.handler.ezprice.contentvathandler'
            - '@ezprice.api.service.vatservice'

    ezprice.api.service.pricewithvatcalculator:
        class: '%ezprice.api.service.pricewithvatcalculator.class%'

    ezprice.api.storage_engine.legacy.handler.ezprice.vathandler:
        class: '%ezprice.api.storage_engine.legacy.handler.ezprice.vathandler.class%'
        factory: ['EzSystems\EzPriceBundle\ApiLoader\LegacyVatHandlerFactory', 'buildLegacyVatHandler']
        arguments:
            - '@service_container'
            - '@ezpublish.api.storage_engine.legacy.dbhandler'

    ezprice.api.storage_engine.legacy.handler.ezprice.contentvathandler:
        class: '%ezprice.api.storage_engine.legacy.handler.ezprice.contentvathandler.class%'
        factory: ['EzSystems\EzPriceBundle\ApiLoader\LegacyContentVatHandlerFactory', 'buildLegacyContentVatHandler']
        arguments:
            - '@service_container'
            - '@ezpublish.api.storage_engine.legacy.dbhandler'
